### ISSUE TITLE
Program won't build because of _curl_easy_* (OS X)

### ISSUE THREAD

**Issue by WillHH** [drowaudio/drowaudio#4]
I've just tried linking DrowAudio on OS X 10.10 using the latest version of JUCE, but after trying to run the program, several errors appear saying undefined symbols for x86_64 (shown in attached screenshot below), is there anything I can do about this?

![screen shot 2015-05-03 at 19 31 05](https://cloud.githubusercontent.com/assets/2125691/7446274/131dfc98-f1cb-11e4-9aad-d33f789cd258.png)

(I'm sorry if this isn't the required format for an issue report, this is my first one.)

**Comment by drowaudio** [comment]
Hi Will, it looks like you’re not linking to cURL.
If you’r not using the cURL class, disable them in the Introjucer with the DROWAUDIO_USE_CURL flag.
If you are using cURL, make sure you add the "-lcurl" flag in the Xcode -> Extra linker flags section of the Introjucer.

Hope that helps,

Dave

**Comment by WillHH** [comment]
Alright, thank you, it's working fine now. :)
