### ISSUE TITLE
License is MIT but dRowAudio directory contains gpl.txt

### ISSUE THREAD

**Issue by jamiebullock** [drowaudio/drowaudio#6]
I assume this is for some historical reason? But it's a bit confusing that dRowAudio contains a gpl.txt when the dRowAudio license is stated as MIT. Probably, either an explanation should be added about the GPL or it should be removed.

**Comment by drowaudio** [comment]
Yes, good point. It is all MIT these days. I will remove the gpl.txt when I get a chance. Thanks!
